# Generated by Django 4.2.7 on 2024-04-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_management", "0002_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="content",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
    ]
