FROM node:latest as builder

WORKDIR /

COPY src/frontend/ src/frontend/

RUN cd src/frontend
RUN cd src/frontend && npm ci
RUN cd src/frontend && npm run build

COPY . .

FROM python:3.11-slim-bookworm

WORKDIR /

COPY --from=builder src/ .

RUN cd src/

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install -U channels["daphne"]
RUN export ENV_FILE_NAME=.env

RUN apt-get -y update
RUN apt-get -y install curl

EXPOSE 8000