version: "3.8"
services:

  cloudsqlproxy:
    container_name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
    volumes:
      - ./creds.json:/secrets/cloudsql/creds.json
    ports:
      - 127.0.0.1:5432:5432
    command: /cloud_sql_proxy -instances="django-cloudrun-project:us-east1:django-dev-db"=tcp:0.0.0.0:5432 -credential_file=/secrets/cloudsql/creds.json
    restart: always
    
  donkey_sponsor_backend:
    container_name: donkey_sponsor_backend
    build: 
      context: ./DonkeySponsorBackend
      dockerfile: Dockerfile.server
    command: bash build.sh
    ports:
      - '8000:8000'
    stdin_open: true
    tty: true
    depends_on:
      - cloudsqlproxy
    networks:
      - donkey_sponsor_network
networks:
  donkey_sponsor_network:

volumes:
  ds_data: