# Generated by Django 4.2.5 on 2024-04-13 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sponsoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonkeyOfSponsor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donkey_of_sponsor', to='sponsoring.animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donkey_of_sponsor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
