# Generated by Django 4.2.5 on 2024-04-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsoring', '0002_donkeyofsponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donkeyofsponsor',
            name='value',
            field=models.FloatField(default=30),
            preserve_default=False,
        ),
    ]
