# Generated by Django 4.2.7 on 2024-04-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsoring", "0003_donkeyofsponsor_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="title",
            field=models.CharField(default=""),
        ),
    ]
