# Generated by Django 4.2.7 on 2024-04-20 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("local_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="local",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="local",
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
