FROM node:latest as builder

WORKDIR /

COPY frontend/ frontend/

RUN cd frontend
RUN cd frontend && npm ci
RUN cd frontend && npm run build

COPY . .

FROM python:3.11-slim-bookworm

WORKDIR /

COPY --from=builder / .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install -U channels["daphne"]
RUN export ENV_FILE_NAME=.env

RUN apt-get -y update
RUN apt-get -y install curl

EXPOSE 8000

CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]